name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./src"
        jupyter: true
        version: "21.5b1"
